### PR TITLE
Constraintlayout ron

### PR DESCRIPTION
**Pull request by roncalapis**
sir Jay, there are 2 new xml files here for the layout. one is the exercise, the other is a something I would like to work on. will send more details later. thanks!

### CODE REVIEW

**Review by jairrab — CHANGES_REQUESTED** [review]
Please target branch "beta-jay" not the "master" branch for the PR

**Comment by jairrab** [comment]
Ron, please file a new PR and target "beta-jay" instead of "master" for the merge

**Comment by roncalapis** [comment]
ok Sir, created a new one to merge into beta-jay

**Comment by roncalapis** [comment]
sir, here's the game app I would like to work on as a practice project. Can
you help me with the layout on how this will be executed, just a high level
and I will researd/study the rest. Thanks!

**Comment by roncalapis** [comment]
Sir, I meant to say on how to do the code for the logic and actual app, I
can do the layout myself

**Pull request closed without merging**
